[package]
name = "lprp"
version = "0.2.0"
authors = ["Masahiko Hamazawa <ichigyo.zanmai@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["parser", "s-expression"]
categories = ["parser"]
description = "lprp is S-expression reader."

[dependencies]
onigiri = "0.1.15"
